#!/usr/bin/env python3
"""
DarkBreaker Agent Commands Syncer
===================================
批量为符合条件的插件/UI 生成或更新 .claude/commands/{implement,repair,audit}.md，
将已形成的 task routing + 脚本体系接入统一命令入口。

用法:
    python3 scripts/sync_agent_commands.py --check       # 预览将生成/更新哪些文件
    python3 scripts/sync_agent_commands.py --apply        # 实际写入
    python3 scripts/sync_agent_commands.py --check --json # JSON 格式预览
"""

import argparse
import json
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# 复用 audit_agent_governance 的治理判断逻辑
# ---------------------------------------------------------------------------

_SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(_SCRIPT_DIR))

from audit_agent_governance import (
    GovernanceResult,
    scan_target,
    scan_all,
    QUALITY_SCRIPTS,
)

# ---------------------------------------------------------------------------
# 常量
# ---------------------------------------------------------------------------

COMMAND_TYPES = ("implement", "repair", "audit")

# 用于判断已有 command 是否"合格" — 必须引用 08_task_routing
ROUTING_ANCHOR = "08_task_routing.md"

# 标记文件头，用于识别同步器生成的文件
SYNC_MARKER = "<!-- auto-generated by sync_agent_commands.py -->"


# ---------------------------------------------------------------------------
# 资格判定
# ---------------------------------------------------------------------------

def is_eligible(gov: GovernanceResult) -> tuple[bool, str]:
    """判断一个对象是否符合生成 commands 的条件。"""
    if gov.governance_level == "L0":
        return False, "L0 占位态，无治理基础"

    if not gov.has_agent_skills:
        return False, "缺少 .agent_skills/ 目录"

    # 必须有 08_task_routing.md
    base = _resolve_base(gov)
    if base and not (base / ".agent_skills" / "08_task_routing.md").is_file():
        return False, "缺少 .agent_skills/08_task_routing.md"

    # 至少有一个可执行脚本
    if not gov.scripts_present:
        # 允许有 tests/ 目录的也算 (可用 pytest 直接跑)
        if "tests" not in gov.dirs_present:
            return False, "无可用脚本且无 tests/ 目录"

    return True, "符合条件"


# 缓存: name -> base path
_BASE_CACHE: dict[str, Path] = {}


def _resolve_base(gov: GovernanceResult) -> Optional[Path]:
    return _BASE_CACHE.get(gov.name)


# ---------------------------------------------------------------------------
# 已有 commands 评估
# ---------------------------------------------------------------------------

@dataclass
class CommandStatus:
    """单个 command 文件的状态。"""
    cmd_type: str
    path: Path
    exists: bool = False
    has_routing_ref: bool = False
    is_auto_generated: bool = False
    action: str = "create"  # create / update / skip
    reason: str = ""


def evaluate_existing_command(base: Path, cmd_type: str) -> CommandStatus:
    """评估一个已有的 command 文件。"""
    cmd_path = base / ".claude" / "commands" / f"{cmd_type}.md"
    status = CommandStatus(cmd_type=cmd_type, path=cmd_path)

    if not cmd_path.is_file():
        status.action = "create"
        status.reason = "文件不存在"
        return status

    status.exists = True
    content = cmd_path.read_text(encoding="utf-8")
    status.has_routing_ref = ROUTING_ANCHOR in content
    status.is_auto_generated = SYNC_MARKER in content

    if status.has_routing_ref and not status.is_auto_generated:
        # 人工编写且已接入路由 — 保留
        status.action = "skip"
        status.reason = "已有合格内容 (人工编写，已接入路由)"
    elif status.is_auto_generated:
        # 自动生成的，可安全更新
        status.action = "update"
        status.reason = "自动生成文件，可安全更新"
    elif not status.has_routing_ref:
        # 存在但未接入路由
        status.action = "update"
        status.reason = "未接入 08_task_routing.md，需更新"
    else:
        status.action = "skip"
        status.reason = "已有合格内容"

    return status


# ---------------------------------------------------------------------------
# 模板生成
# ---------------------------------------------------------------------------

def _script_line(script_name: str, base: Path, module_placeholder: str = "<module>") -> str:
    """生成脚本调用行，标注是否真实存在。"""
    exists = (base / "scripts" / script_name).is_file()
    cmd = f"./scripts/{script_name}"
    if "targeted" in script_name:
        cmd += f" {module_placeholder}"
    if exists:
        return f"   - `{cmd}` — 等待实际输出"
    return f"   - ~~`{cmd}`~~ — 脚本不存在，跳过"


def _get_available_scripts(gov: GovernanceResult, base: Path, task: str) -> list[str]:
    """获取该任务类型下可用的脚本列表。"""
    # 按任务类型和治理等级返回应使用的脚本 (只返回存在的)
    candidates = {
        "implement": [
            "run_targeted_tests.sh",
            "run_regression_tests.sh",
            "run_quality_gate.sh",
        ],
        "repair": [
            "run_targeted_tests.sh",
            "run_regression_tests.sh",
            "collect_root_cause.sh",
        ],
        "audit": [
            "run_quality_gate.sh",
            "run_regression_tests.sh",
        ],
    }

    if gov.object_type == "ui":
        candidates = {
            "implement": [
                "check_ui_contract.sh",
                "check_three_state_coverage.sh",
                "run_quality_gate.sh",
            ],
            "repair": [
                "check_ui_contract.sh",
                "collect_root_cause.sh",
            ],
            "audit": [
                "check_ui_contract.sh",
                "check_three_state_coverage.sh",
                "run_quality_gate.sh",
            ],
        }

    all_scripts = candidates.get(task, [])
    # 对 MIN 级降级到 sanity
    if gov.governance_level == "MIN":
        all_scripts = ["run_sanity_checks.sh"]

    return all_scripts


# -- 读取顺序 --

def _read_order_implement(gov: GovernanceResult) -> str:
    if gov.object_type == "ui":
        return """1. `PROJECT_CARD.md` — 确认业务目标
2. `CLAUDE.md` — 确认固定指令与阻断条件
3. `.agent_skills/00_project_context.md` — 项目上下文
4. `.agent_skills/01_architecture_rules.md` — 架构红线
5. `.agent_skills/02_ui_contract.md` — UI 契约
6. `.agent_skills/03_test_strategy.md` — 测试分层
7. `.agent_skills/05_security_boundary.md` — 安全边界"""

    return """1. `PROJECT_CARD.md` — 确认业务目标
2. `CLAUDE.md` — 确认固定指令与阻断条件
3. `.agent_skills/00_project_context.md` — 项目上下文
4. `.agent_skills/01_architecture_rules.md` — 架构红线
5. `.agent_skills/02_algorithm_contract.md` — 算法契约
6. `.agent_skills/03_test_strategy.md` — 测试分层
7. `configs/default.yaml` — 当前配置基线"""


def _read_order_repair(gov: GovernanceResult) -> str:
    if gov.object_type == "ui":
        return """1. `PROJECT_CARD.md` — 确认业务目标
2. `CLAUDE.md` — 确认固定指令与阻断条件
3. `.agent_skills/00_project_context.md` — 项目上下文
4. `.agent_skills/01_architecture_rules.md` — 架构红线
5. `.agent_skills/04_quality_audit.md` — 定位违规项
6. `.agent_skills/03_test_strategy.md` — 测试分层
7. `.agent_skills/07_learning_log.md` — 检查是否已知问题"""

    return """1. `PROJECT_CARD.md` — 确认业务目标
2. `CLAUDE.md` — 确认固定指令与阻断条件
3. `.agent_skills/00_project_context.md` — 项目上下文
4. `.agent_skills/01_architecture_rules.md` — 架构红线
5. `.agent_skills/02_algorithm_contract.md` — 确认预期行为
6. `.agent_skills/07_learning_log.md` — 检查是否已知问题
7. `.agent_skills/06_refactor_policy.md` — 确认修复边界"""


def _read_order_audit(gov: GovernanceResult) -> str:
    if gov.object_type == "ui":
        return """1. `PROJECT_CARD.md` — 确认业务目标
2. `CLAUDE.md` — 确认固定指令与阻断条件
3. `.agent_skills/00_project_context.md` — 项目上下文
4. `.agent_skills/01_architecture_rules.md` — 架构红线
5. `.agent_skills/04_quality_audit.md` — 审计清单与命令
6. `.agent_skills/03_test_strategy.md` — 测试分层
7. `.agent_skills/02_ui_contract.md` — UI 契约（验收条件）"""

    lines = """1. `PROJECT_CARD.md` — 确认业务目标
2. `CLAUDE.md` — 确认固定指令与阻断条件
3. `.agent_skills/00_project_context.md` — 项目上下文
4. `.agent_skills/01_architecture_rules.md` — 架构红线
5. `.agent_skills/04_quality_audit.md` — 审计清单与命令
6. `.agent_skills/05_security_boundary.md` — 安全边界"""
    if ((_resolve_base(gov) or Path()) / ".coveragerc").is_file():
        lines += "\n7. `.coveragerc` — 当前覆盖率门槛"
    return lines


# -- 层级边界描述 --

def _layer_boundary(gov: GovernanceResult) -> str:
    """根据对象类型生成层级边界说明。"""
    t = gov.object_type
    if t == "plugin-enhanced-detector":
        return "detector_enhanced 层禁止依赖 SDK；配置必须经适配器进入算法层"
    if t == "plugin-light-detector":
        return "detector 层禁止依赖 SDK；plugin.py 不含算法逻辑"
    if t == "plugin-service-integration":
        return "core/ 不依赖 SDK；plugin.py 仅做编排和数据转换"
    if t == "plugin-minimal":
        return "plugin.py 不含硬编码阈值；所有配置从 configs/ 加载"
    if t == "ui":
        return "UI 层禁止直接访问数据库或后端内部 API；所有数据经 API 网关"
    return "遵循架构分层，不跨越模块边界"


# -- 模板主体 --

def generate_implement(gov: GovernanceResult, base: Path) -> str:
    scripts = _get_available_scripts(gov, base, "implement")
    script_lines = "\n".join(_script_line(s, base) for s in scripts)
    fallback = ""
    if not any((base / "scripts" / s).is_file() for s in scripts):
        fallback = "\n   - `python -m pytest tests/ -q` — 直接 pytest 验证"

    return f"""{SYNC_MARKER}
# /implement

适用于功能或规则实现。

## 强制前置

**必须先读取 `.agent_skills/08_task_routing.md` 中 `implement` 路由表。**

## 文件读取顺序（不可跳过）

{_read_order_implement(gov)}

## 执行流程

1. **重述目标与约束** — 用一句话写清本次要实现什么，引用约束编号。
2. **先写测试** — 在 `tests/` 下新增或更新契约测试。
3. **最小实现** — 不跨越层级边界（{_layer_boundary(gov)}）。
4. **验证**:
{script_lines}{fallback}

## 输出格式

```text
[PLAN]
- 目标模块
- 约束条目（引用规则文件 + 条目编号）
- 测试清单

[EXECUTION]
- 实际改动文件（含行号范围）
- 测试结果（粘贴实际输出）

[DELIVERY]
- 残余风险
- 未决人工确认项
```

## 禁止行为

- 不得跳过测试直接提交实现
- 不得仅给出"流程摘要"而不执行实际命令
- 不得在未读取上述文件的情况下开始编码
- 不得新增硬编码业务阈值到推理路径
"""


def generate_repair(gov: GovernanceResult, base: Path) -> str:
    scripts = _get_available_scripts(gov, base, "repair")
    script_lines = "\n".join(_script_line(s, base) for s in scripts)
    fallback = ""
    if not any((base / "scripts" / s).is_file() for s in scripts):
        fallback = "\n   - `python -m pytest tests/ -q` — 直接 pytest 验证"

    return f"""{SYNC_MARKER}
# /repair

适用于缺陷修复。

## 强制前置

**必须先读取 `.agent_skills/08_task_routing.md` 中 `repair` 路由表。**

## 文件读取顺序（不可跳过）

{_read_order_repair(gov)}

## 执行流程

1. **记录现象** — 现象、复现步骤、首次失败边界。
2. **先写失败测试** — 测试必须能复现缺陷，运行确认红灯。
3. **最小因果修复** — 只修当前根因，不做无关重构。不跨越层级边界（{_layer_boundary(gov)}）。
4. **验证**:
{script_lines}{fallback}
5. **必须追加**根因条目到 `.agent_skills/07_learning_log.md`。

## 输出格式

```text
[SYMPTOM]
- 现象描述
- 复现路径

[ROOT CAUSE]
- 根因分析

[FIX]
- 改动文件与行号
- 失败测试 -> 通过测试（粘贴实际输出）

[REGRESSION]
- 回归测试结果（粘贴实际输出）

[LEARNING LOG]
- 追加的 07_learning_log 条目摘要

[RESIDUAL RISK]
- 残余风险与人工确认项
```

## 禁止行为

- 不得跳过失败测试直接修复
- 不得遗漏 learning_log 回写
- 不得借修复之名做无关重构
"""


def generate_audit(gov: GovernanceResult, base: Path) -> str:
    scripts = _get_available_scripts(gov, base, "audit")
    script_lines = "\n".join(_script_line(s, base) for s in scripts)
    fallback = ""
    if not any((base / "scripts" / s).is_file() for s in scripts):
        fallback = "\n   - `python -m pytest tests/ -q` — 直接 pytest 验证"

    return f"""{SYNC_MARKER}
# /audit

适用于提测/交付前质量审计。

## 强制前置

**必须先读取 `.agent_skills/08_task_routing.md` 中 `audit` 路由表。**

## 文件读取顺序（不可跳过）

{_read_order_audit(gov)}

## 执行流程

1. **执行质量闸门**:
{script_lines}{fallback}
   等待实际输出。
2. **安全扫描** — 按 `05_security_boundary.md` 中的可执行安全检查逐条运行。等待实际输出。
3. **人工审查** — 按 `04_quality_audit.md` 的高/中优先级审计项逐条检查。
4. **分级输出** — 按下方模板输出结论。

## 输出格式（强制）

```text
[AUDIT_RESULT] PASS|FAIL

[BLOCKERS]
<阻断项列表，空则写 NONE>

[HIGH_RISK]
<高风险项列表，空则写 NONE>

[ACTION_ITEMS]
<必须执行的修复动作，按优先级排序>

[EVIDENCE]
- 质量闸门输出（粘贴关键段落）
- 安全扫描输出（粘贴关键段落）
- 覆盖率数据
```

## 禁止行为

- 不得在未实际执行命令的情况下宣称 PASS
- 不得修改生产代码（审计只读）
- 不得省略 EVIDENCE 段落
"""


GENERATORS = {
    "implement": generate_implement,
    "repair": generate_repair,
    "audit": generate_audit,
}

# ---------------------------------------------------------------------------
# 同步计划
# ---------------------------------------------------------------------------

@dataclass
class SyncAction:
    target_name: str
    target_type: str
    governance_level: str
    cmd_type: str
    path: str
    action: str  # create / update / skip
    reason: str


def build_sync_plan(repo_root: Path) -> tuple[list[SyncAction], list[dict]]:
    """构建同步计划，返回 (actions, ineligible_list)。"""
    results = scan_all(repo_root)
    actions = []
    ineligible = []

    for gov in results:
        # 缓存 base path
        if gov.scope == "root":
            base = repo_root
        elif gov.scope == "ui":
            base = repo_root / "ui"
        else:
            base = repo_root / "plugins" / gov.name
        _BASE_CACHE[gov.name] = base

        # root 不生成 commands (总路由角色)
        if gov.scope == "root":
            ineligible.append({
                "name": gov.name, "reason": "root 是总路由角色，不生成插件级 commands",
            })
            continue

        eligible, reason = is_eligible(gov)
        if not eligible:
            ineligible.append({"name": gov.name, "reason": reason})
            continue

        for cmd_type in COMMAND_TYPES:
            status = evaluate_existing_command(base, cmd_type)
            actions.append(SyncAction(
                target_name=gov.name,
                target_type=gov.object_type,
                governance_level=gov.governance_level,
                cmd_type=cmd_type,
                path=str(status.path),
                action=status.action,
                reason=status.reason,
            ))

    return actions, ineligible


# ---------------------------------------------------------------------------
# 执行写入
# ---------------------------------------------------------------------------

def apply_sync(repo_root: Path, actions: list[SyncAction]) -> list[dict]:
    """执行同步写入，返回结果列表。"""
    results_log = []

    for act in actions:
        if act.action == "skip":
            results_log.append({
                "target": act.target_name,
                "cmd": act.cmd_type,
                "action": "skip",
                "reason": act.reason,
            })
            continue

        # 解析 base
        base = _BASE_CACHE.get(act.target_name)
        if not base:
            continue

        # 获取治理信息
        scope = "ui" if act.target_name == "ui" else "plugin"
        gov = scan_target(act.target_name, base, scope)
        _BASE_CACHE[gov.name] = base

        # 生成内容
        generator = GENERATORS.get(act.cmd_type)
        if not generator:
            continue

        content = generator(gov, base)

        # 写入
        cmd_path = Path(act.path)
        cmd_path.parent.mkdir(parents=True, exist_ok=True)
        cmd_path.write_text(content, encoding="utf-8")

        results_log.append({
            "target": act.target_name,
            "cmd": act.cmd_type,
            "action": act.action,
            "path": str(cmd_path),
            "reason": act.reason,
        })

    return results_log


# ---------------------------------------------------------------------------
# 输出格式化
# ---------------------------------------------------------------------------

def format_check_output(actions: list[SyncAction], ineligible: list[dict]) -> str:
    lines = []
    sep = "=" * 78

    # 不符合条件的对象
    lines.append(sep)
    lines.append("[不符合生成条件的对象]")
    lines.append(sep)
    if ineligible:
        for item in ineligible:
            lines.append(f"  ✗ {item['name']:<28} — {item['reason']}")
    else:
        lines.append("  (无)")
    lines.append("")

    # 按 action 分组
    creates = [a for a in actions if a.action == "create"]
    updates = [a for a in actions if a.action == "update"]
    skips = [a for a in actions if a.action == "skip"]

    lines.append(sep)
    lines.append(f"[同步计划] 新建: {len(creates)} / 更新: {len(updates)} / 跳过: {len(skips)}")
    lines.append(sep)

    # 按目标分组展示
    targets = {}
    for a in actions:
        targets.setdefault(a.target_name, []).append(a)

    for name, acts in sorted(targets.items()):
        level = acts[0].governance_level
        obj_type = acts[0].target_type
        lines.append(f"\n  {name} ({obj_type}, {level}):")
        for a in acts:
            icon = {"create": "+", "update": "~", "skip": "="}[a.action]
            lines.append(f"    [{icon}] {a.cmd_type:12} — {a.action:6} | {a.reason}")

    lines.append("")
    return "\n".join(lines)


def format_apply_output(results_log: list[dict]) -> str:
    lines = ["", "=" * 78, "[同步结果]", "=" * 78]
    created = sum(1 for r in results_log if r["action"] == "create")
    updated = sum(1 for r in results_log if r["action"] == "update")
    skipped = sum(1 for r in results_log if r["action"] == "skip")

    for r in results_log:
        icon = {"create": "✓ 新建", "update": "✓ 更新", "skip": "— 跳过"}[r["action"]]
        path_str = f"  → {r.get('path', '')}" if r.get("path") else ""
        lines.append(f"  {icon} {r['target']}/{r['cmd']}.md{path_str}")

    lines.append(f"\n  汇总: {created} 新建 / {updated} 更新 / {skipped} 跳过")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 主函数
# ---------------------------------------------------------------------------

def find_repo_root() -> Path:
    cwd = Path.cwd()
    if (cwd / "plugins").is_dir() and (cwd / "platform_core").is_dir():
        return cwd
    script_dir = Path(__file__).resolve().parent.parent
    if (script_dir / "plugins").is_dir():
        return script_dir
    return cwd


def main():
    parser = argparse.ArgumentParser(
        description="DarkBreaker Agent Commands Syncer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
  %(prog)s --check            预览将生成/更新哪些文件
  %(prog)s --apply            实际写入
  %(prog)s --check --json     JSON 格式预览
""",
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="预览模式，不写入文件")
    mode.add_argument("--apply", action="store_true", help="执行写入")
    parser.add_argument("--json", action="store_true", help="JSON 格式输出")
    parser.add_argument("--root", type=str, default=None, help="指定仓库根目录")
    args = parser.parse_args()

    repo_root = Path(args.root) if args.root else find_repo_root()
    if not (repo_root / "plugins").is_dir():
        print(f"错误: {repo_root} 不是有效的 DarkBreaker 仓库根目录", file=sys.stderr)
        sys.exit(1)

    actions, ineligible = build_sync_plan(repo_root)

    if args.check:
        if args.json:
            data = {
                "ineligible": ineligible,
                "actions": [
                    {
                        "target": a.target_name,
                        "type": a.target_type,
                        "level": a.governance_level,
                        "cmd": a.cmd_type,
                        "action": a.action,
                        "reason": a.reason,
                        "path": a.path,
                    }
                    for a in actions
                ],
            }
            print(json.dumps(data, ensure_ascii=False, indent=2))
        else:
            print(format_check_output(actions, ineligible))
        return

    if args.apply:
        # 先展示计划
        print(format_check_output(actions, ineligible))

        # 执行
        results_log = apply_sync(repo_root, actions)
        print(format_apply_output(results_log))


if __name__ == "__main__":
    main()
